<a href="https://colab.research.google.com/github/gow504/Text-Preprocessing-Using-NLP/blob/main/text_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

text preprocessing with **NLP**

q)what is the use of this project?

A)  This project appears to be focused on Natural Language Processing (NLP) text preprocessing, specifically for sentiment analysis or a similar text-based task.

steps for text preprocessing

1.Lowercasing


2.Removing HTML Tags, URLs, and Punctuation

3.Removing Stop Words

4.Tokenization

5.Handling Emojis

6.Tokenization

7.Stemming and Lemmatization:

In [35]:
import pandas as pd
import re

In [4]:
df = pd.read_csv("/content/IMDB Dataset.csv")

In [5]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [8]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [9]:
df.shape

(50000, 2)

In [10]:
#lowercasing
df['review']=df['review'].str.lower()

In [11]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [12]:
#remove html tags
def remove_html(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'',text)                 #r' ' means a raw string

In [13]:
df['review']=df['review'].apply(remove_html)

In [14]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [15]:
#remove url's
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www.\.S+')     # S+ =This is a special sequence that matches any non-whitespace character.
  return pattern.sub(r' ',text)

In [16]:
df['review']=df['review'].apply(remove_url)

In [17]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [18]:
# remove punctuation
import string,time        # The string module contains a collection of useful string constants.
string.punctuation        # The time module provides functions for working with time,

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [19]:
exclude= string.punctuation

In [20]:
def remove_punc(text):
  return text.translate(str.maketrans('','',exclude)) # make trans = mapping to exclude.
                                                      # text.translate(...):This is a string method called on the text input string.

In [21]:
df['review']=df['review'].apply(remove_punc)

In [22]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [23]:
#remove stopwords
from nltk.corpus import stopwords
import nltk

In [24]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [25]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [26]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [27]:
df['review'] = df['review'].apply(remove_stopwords)

In [28]:
df

                                                  review sentiment
0      one    reviewers  mentioned   watching  1 oz e...  positive
1       wonderful little production  filming techniqu...  positive
2       thought    wonderful way  spend time    hot s...  positive
3      basically theres  family   little boy jake thi...  negative
4      petter matteis love   time  money   visually s...  positive
...                                                  ...       ...
49995   thought  movie    right good job  wasnt  crea...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997     catholic taught  parochial elementary schoo...  negative
49998  im going    disagree   previous comment  side ...  negative
49999   one expects  star trek movies   high art   fa...  negative

[50000 rows x 2 columns]

In [29]:
# handling Emoji's
'''
we have two options
1) replace emoji's with text
2) remove emoji's
'''

def remove_emoji(text):
    emoji_pattern = re.compile("["
                               "u\U0001F600-\U0001F64F"  # Emotions
                               "u\U0001F300-\U0001F5FF"  # Symbols & pictographs
                               "u\U0001F680-\U0001F6FF"  # Transport & map symbols
                               "u\U0001F1E0-\U0001F1FF"  # Flags(iOS)
                               "u\U00002702-\U000027B0"
                               "u\U000024C2-\U0001F251"
                               "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [30]:
remove_emoji("i am gowtham 😁")

'i am gowtham '

In [31]:
! pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 15.4 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [32]:
import emoji
print(emoji.demojize('ai is ❤️'))

ai is :red_heart:

tokenization
there are different types of tokenizations

1) word tokenization
2) sentence tokenization


Q)why we will do tokenization

A)  it breaks down raw text into smaller, meaningful units called tokens.reduce the number of unique tokens (vocabulary size) and normalize the text and  **fixed context window in LLM's**

In [33]:
# word tokenization
a= 'i am gowtham'
a.split()

['i', 'am', 'gowtham']

In [37]:
# sentence tokenization
b= 'i am gowtham.  i am studying python! '
b.split('.')

['i am gowtham', '  i am studying python! ']

In [38]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [39]:
nltk.download('punkt')              # The punkt tokenizer is a pre-trained model that NLTK uses to perform advanced tokenization, specifically for breaking text into a list of sentences (sent_tokenize) and words (word_tokenize
nltk.download('punkt_tab')
                                          #This line downloads an additional punkt tokenizer mode

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [41]:
sent1 = 'I am going to visit delhi!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [45]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [46]:
from nltk.stem.porter import PorterStemmer

In [56]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [57]:
from nltk.stem.porter import PorterStemmer
import nltk

ps = PorterStemmer()

# Using the sample text from earlier for consistent comparison
text_for_stemming = "probably my all time favourite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen some 15 or more times in the last 25 years."

# Tokenize the text into words
words_to_stem = nltk.word_tokenize(text_for_stemming)

print("{0:20}{1:20}".format("Word","Stem"))
print("-" * 40)
for word in words_to_stem:
    print("{0:20}{1:20}".format(word, ps.stem(word)))

Word                Stem
----------------------------------------
probably            probabl
my                  my
all                 all
time                time
favourite           favourit
movie               movi
a                   a
story               stori
of                  of
selflessness        selfless
sacrifice           sacrific
and                 and
dedication          dedic
to                  to
a                   a
noble               nobl
cause               caus
but                 but
its                 it
not                 not
preachy             preachi
or                  or
boring              bore
it                  it
just                just
never               never
gets                get
old                 old
despite             despit
my                  my
having              have
seen                seen
some                some
15                  15
or                  or
more                more
times               time
in                  in
the                 the
last                last
25                  25
years               year
.                   .

Here after doing stemming the words like probably, movie, sacrifice etc are converted to probabl, movi, sacrific

In [51]:
import nltk
from nltk.stem import WordNetLemmatizer

In [52]:
# Download the WordNet corpus
nltk.download('wordnet')          # large and structured set of texts (or speech).

# You might also need to download the 'omw-1.4' package for wordnet
nltk.download('omw-1.4')          #  OMW, collection of wordnets for various languages

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [53]:
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "probably my all time favourite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen some 15 or more times in the last 25 years."
punctuations = "?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

Word                Lemma
probably            probably
my                  my
all                 all
time                time
favourite           favourite
movie               movie
a                   a
story               story
of                  of
selflessness        selflessness
sacrifice           sacrifice
and                 and
dedication          dedication
to                  to
a                   a
noble               noble
cause               cause
but                 but
its                 its
not                 not
preachy             preachy
or                  or
boring              bore
it                  it
just                just
never               never
gets                get
old                 old
despite             despite
my                  my
having              have
seen                see
some                some
15                  15
or                  or
more                more
times               time
in                  in
the                 the
last                last
25                  25
years               years